#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
echo "------------------------------------------------------------------------"
echo "Adding id_rsa_github key to SSH agent and test github connection"
echo "------------------------------------------------------------------------"
ssh-add /home/nn/.ssh/id_rsa_github
ssh -T git@github.com
