#!/bin/bash
#   _  ___  __                         
#  / |/ / |/ /
# /    /    /   
#/_/|_/_/|_/  
#
# 20200413 - First script for updating ReverseProxy VM
# 20200319 - Added checking logs for maintenance
# 20200319 - (1)Added testing disk access speed
#            https://www.debian.org/doc/manuals/debian-reference/ch09.en.html
# 20200515 - Refreshed look, added Debian Versioning
# 20220118 - Updated script, added certbot renewal check
#
echo "------------------------------------------"
echo "--[ Debian Version $(cat /etc/debian_version), Update? (y/n) ]--"
echo "------------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------"
  echo "--[ Updating Debian ]--"
  echo "-----------------------"
  sudo apt update
  echo "------------------------"
  echo "--[ Upgrading Debian ]--"
  echo "------------------------"
  sudo apt upgrade
  echo "-------------------------"
  echo "--[ Running autoclean ]--"
  echo "-------------------------"
  sudo apt autoclean
  echo "--------------------------"
  echo "--[ Running autoremove ]--"
  echo "--------------------------"
  sudo apt autoremove
fi
echo "-----------------------------------------------------"
echo "--[ Check certbot for certificate renewals? (y/n) ]--"
echo "-----------------------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------------------------"
  echo "--[ Checking for certificate renewals ]--"
  echo "-----------------------------------------"
  sudo certbot renew
fi
echo "------------------------"
echo "--[ Updating mlocate ]--"
echo "------------------------"
sudo updatedb
echo "-------------------------"
echo "--[ Check Logs? (y/n) ]--"
echo "-------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "---------------------------------------"
  echo "--[ Checking Unattended Updates log ]--"
  echo "---------------------------------------"
  sudo tail -n 5 /var/log/unattended-upgrades/unattended-upgrades.log
  echo "---------------------------------------"
  echo "--[ Checking if fail2ban is running ]--"
  echo "---------------------------------------"
  sudo fail2ban-client status
  echo "---------------------------"
  echo "--[ Checking UFW status ]--"
  echo "---------------------------"
  sudo ufw status
  echo "--------------------------------------"
  echo "--[ Check Disk Access Speed? (y/n) ]--"
  echo "--------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "---------------------------------"
    echo "--[ Testing disk access speed ]--"
    echo "---------------------------------"
    sudo hdparm -tT /dev/sda1
  fi
  echo "--------------------------------"
  echo "--[ Run rkhunter scan? (y/n) ]--"
  echo "--------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  echo "-----------------------------"
  echo "--[ Running rkhunter scan ]--"
  echo "-----------------------------"
  sudo rkhunter --check --rwo
  fi
fi